name: bookia
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.1.0
  gap: ^3.0.1
  go_router: any
  pinput: ^5.0.1
  dio: ^5.8.0+1
  http: ^1.4.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  lottie: ^3.3.1
  shared_preferences: ^2.5.3
  carousel_slider: ^5.1.1
  smooth_page_indicator: ^1.2.1
  skeletonizer: ^2.0.1
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    
    - Assets\Icons\back.svg
    - Assets\Icons\Bookmark.svg
    - Assets\Icons\camera.svg
    - Assets\Icons\Category.svg
    - Assets\Icons\close.svg
    - Assets\Icons\fluent_eye-20-filled.svg
    - Assets\Icons\Home.svg
    - Assets\Icons\Logout.svg
    - Assets\Icons\Profile.svg
    - Assets\Icons\search-normal.svg
    - Assets\Images\Apple.svg
    - Assets\Images\Facebook (Button).svg
    - Assets\Images\Google (Button).svg
    - Assets\Images\logo.svg
    - Assets\Images\Successmark (1).svg
    - Assets\Images\alif-caesar-rizqi-pratama-loUlSOXL81c-unsplash 1.png
    - Assets\Icons\fluent_eye-20-filled.svg
    - Assets\Images\Animation - 1750456177238.json
   
    

  fonts:
    - family: DMSerifDisplay
      fonts:
        - asset: Assets\Fonts\DMSerifDisplay-Regular.ttf
  
